
/* Autogenerated file, do not edit! */

// @ts-nocheck

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import TokenContractArtifactJson from './artifacts/token_contract-Token.json' with { type: 'json' };
export const TokenContractArtifact = loadContractArtifact(TokenContractArtifactJson as NoirCompiledContract);


      export type Transfer = {
        from: AztecAddressLike
to: AztecAddressLike
amount: (bigint | number)
      }
    

/**
 * Type-safe interface for contract Token;
 */
export class TokenContract extends ContractBase {
  
  protected constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, TokenContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): TokenContract {
    return Contract.at(address, TokenContract.artifact, wallet) as TokenContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, name: string, symbol: string, decimals: (bigint | number), initial_supply: (bigint | number), to: AztecAddressLike) {
    return new DeployMethod<TokenContract>(PublicKeys.default(), wallet, TokenContractArtifact, (instance, wallet) => TokenContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, name: string, symbol: string, decimals: (bigint | number), initial_supply: (bigint | number), to: AztecAddressLike) {
    return new DeployMethod<TokenContract>(publicKeys, wallet, TokenContractArtifact, (instance, wallet) => TokenContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TokenContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<TokenContract['methods'][M]>
  ) {
    return new DeployMethod<TokenContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      TokenContractArtifact,
      (instance, wallet) => TokenContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TokenContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(TokenContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'name' | 'symbol' | 'decimals' | 'private_balances' | 'total_supply' | 'public_balances' | 'minter'> {
      return {
        name: {
      slot: new Fr(1n),
    },
symbol: {
      slot: new Fr(3n),
    },
decimals: {
      slot: new Fr(5n),
    },
private_balances: {
      slot: new Fr(7n),
    },
total_supply: {
      slot: new Fr(8n),
    },
public_balances: {
      slot: new Fr(9n),
    },
minter: {
      slot: new Fr(10n),
    }
      } as ContractStorageLayout<'name' | 'symbol' | 'decimals' | 'private_balances' | 'total_supply' | 'public_balances' | 'minter'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** balance_of_private(owner: struct) */
    balance_of_private: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** balance_of_public(owner: struct) */
    balance_of_public: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn_private(from: struct, amount: integer, _nonce: field) */
    burn_private: ((from: AztecAddressLike, amount: (bigint | number), _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn_public(from: struct, amount: integer, _nonce: field) */
    burn_public: ((from: AztecAddressLike, amount: (bigint | number), _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor_with_initial_supply(name: string, symbol: string, decimals: integer, initial_supply: integer, to: struct) */
    constructor_with_initial_supply: ((name: string, symbol: string, decimals: (bigint | number), initial_supply: (bigint | number), to: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor_with_minter(name: string, symbol: string, decimals: integer, minter: struct) */
    constructor_with_minter: ((name: string, symbol: string, decimals: (bigint | number), minter: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** decimals() */
    decimals: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize_transfer_commitment(to: struct, completer: struct) */
    initialize_transfer_commitment: ((to: AztecAddressLike, completer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_to_commitment(commitment: field, amount: integer) */
    mint_to_commitment: ((commitment: FieldLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_to_private(to: struct, amount: integer) */
    mint_to_private: ((to: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_to_public(to: struct, amount: integer) */
    mint_to_public: ((to: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** name() */
    name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** symbol() */
    symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** total_supply() */
    total_supply: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private_to_commitment(from: struct, commitment: field, amount: integer, _nonce: field) */
    transfer_private_to_commitment: ((from: AztecAddressLike, commitment: FieldLike, amount: (bigint | number), _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private_to_private(from: struct, to: struct, amount: integer, _nonce: field) */
    transfer_private_to_private: ((from: AztecAddressLike, to: AztecAddressLike, amount: (bigint | number), _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private_to_public(from: struct, to: struct, amount: integer, _nonce: field) */
    transfer_private_to_public: ((from: AztecAddressLike, to: AztecAddressLike, amount: (bigint | number), _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private_to_public_with_commitment(from: struct, to: struct, amount: integer, _nonce: field) */
    transfer_private_to_public_with_commitment: ((from: AztecAddressLike, to: AztecAddressLike, amount: (bigint | number), _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_public_to_commitment(from: struct, commitment: field, amount: integer, _nonce: field) */
    transfer_public_to_commitment: ((from: AztecAddressLike, commitment: FieldLike, amount: (bigint | number), _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_public_to_private(from: struct, to: struct, amount: integer, _nonce: field) */
    transfer_public_to_private: ((from: AztecAddressLike, to: AztecAddressLike, amount: (bigint | number), _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_public_to_public(from: struct, to: struct, amount: integer, _nonce: field) */
    transfer_public_to_public: ((from: AztecAddressLike, to: AztecAddressLike, amount: (bigint | number), _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { Transfer: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Transfer: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "to",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        }
    ],
    "path": "Token::Transfer"
},
        eventSelector: EventSelector.fromString("0x70a1894e"),
        fieldNames: ["from","to","amount"],
      }
    };
  }
  
}
