
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import AnonymousVotingContractArtifactJson from '../../contracts/target/anonymous_voting-AnonymousVoting.json' with { type: 'json' };
export const AnonymousVotingContractArtifact = loadContractArtifact(AnonymousVotingContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract AnonymousVoting;
 */
export class AnonymousVotingContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, AnonymousVotingContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): AnonymousVotingContract {
    return Contract.at(address, AnonymousVotingContract.artifact, wallet) as AnonymousVotingContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, operator: AztecAddressLike, num_candidates: (bigint | number), instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<AnonymousVotingContract>(
      wallet,
      {
        artifact: AnonymousVotingContractArtifact,
        postDeployCtor: (instance, wallet) => AnonymousVotingContract.at(instance.address, wallet),
        args: [operator, num_candidates],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AnonymousVotingContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<AnonymousVotingContract['methods'][M]>
  ) {
    return DeployMethod.create<AnonymousVotingContract>(
      opts.wallet,
      {
        artifact: AnonymousVotingContractArtifact,
        postDeployCtor: (instance, wallet) => AnonymousVotingContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AnonymousVotingContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(AnonymousVotingContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'operator' | 'num_candidates' | 'eligible_root' | 'tally' | 'total_votes' | 'voted' | 'demo_claims'> {
      return {
        operator: {
      slot: new Fr(1n),
    },
num_candidates: {
      slot: new Fr(3n),
    },
eligible_root: {
      slot: new Fr(5n),
    },
tally: {
      slot: new Fr(6n),
    },
total_votes: {
      slot: new Fr(7n),
    },
voted: {
      slot: new Fr(8n),
    },
demo_claims: {
      slot: new Fr(9n),
    }
      } as ContractStorageLayout<'operator' | 'num_candidates' | 'eligible_root' | 'tally' | 'total_votes' | 'voted' | 'demo_claims'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** demo_vote(candidate: field) */
    demo_vote: ((candidate: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_eligible_root() */
    get_eligible_root: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_tally(candidate: field) */
    get_tally: ((candidate: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_votes() */
    get_total_votes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(operator: struct, num_candidates: integer) */
    init: ((operator: AztecAddressLike, num_candidates: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_voted(nullifier: field) */
    is_voted: ((nullifier: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** publish_eligible_root(new_root: field) */
    publish_eligible_root: ((new_root: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** vote(secret: field, leaf_index: field, sibling_path: array, candidate: field) */
    vote: ((secret: FieldLike, leaf_index: FieldLike, sibling_path: FieldLike[], candidate: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
