
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import BaseBridgeContractArtifactJson from '../../contracts/target/base_bridge-BaseBridge.json' with { type: 'json' };
export const BaseBridgeContractArtifact = loadContractArtifact(BaseBridgeContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract BaseBridge;
 */
export class BaseBridgeContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, BaseBridgeContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): BaseBridgeContract {
    return Contract.at(address, BaseBridgeContract.artifact, wallet) as BaseBridgeContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, portal_address: EthAddressLike) {
    return new DeployMethod<BaseBridgeContract>(PublicKeys.default(), wallet, BaseBridgeContractArtifact, (instance, wallet) => BaseBridgeContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, portal_address: EthAddressLike) {
    return new DeployMethod<BaseBridgeContract>(publicKeys, wallet, BaseBridgeContractArtifact, (instance, wallet) => BaseBridgeContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BaseBridgeContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<BaseBridgeContract['methods'][M]>
  ) {
    return new DeployMethod<BaseBridgeContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      BaseBridgeContractArtifact,
      (instance, wallet) => BaseBridgeContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BaseBridgeContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(BaseBridgeContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'portal_address'> {
      return {
        portal_address: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'portal_address'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** bridge_private(input_asset: struct, input_asset_bridge: struct, input_amount: integer, base_recipient: struct, base_min_gas_limit: field, nonce_for_transfer_to_public_approval: field, caller_on_L1: struct) */
    bridge_private: ((input_asset: AztecAddressLike, input_asset_bridge: AztecAddressLike, input_amount: (bigint | number), base_recipient: EthAddressLike, base_min_gas_limit: FieldLike, nonce_for_transfer_to_public_approval: FieldLike, caller_on_L1: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(portal_address: struct) */
    constructor: ((portal_address: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
