
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import BatchPayContractArtifactJson from '../../contracts/target/batch_pay-BatchPay.json' with { type: 'json' };
export const BatchPayContractArtifact = loadContractArtifact(BatchPayContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract BatchPay;
 */
export class BatchPayContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, BatchPayContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): BatchPayContract {
    return Contract.at(address, BatchPayContract.artifact, wallet) as BatchPayContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, payment_token: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<BatchPayContract>(
      wallet,
      {
        artifact: BatchPayContractArtifact,
        postDeployCtor: (instance, wallet) => BatchPayContract.at(instance.address, wallet),
        args: [payment_token],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BatchPayContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<BatchPayContract['methods'][M]>
  ) {
    return DeployMethod.create<BatchPayContract>(
      opts.wallet,
      {
        artifact: BatchPayContractArtifact,
        postDeployCtor: (instance, wallet) => BatchPayContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BatchPayContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(BatchPayContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'payment_token'> {
      return {
        payment_token: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'payment_token'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** init(payment_token: struct) */
    init: ((payment_token: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** pay_three(to1: struct, amount1: integer, nonce1: field, to2: struct, amount2: integer, nonce2: field, to3: struct, amount3: integer, nonce3: field) */
    pay_three: ((to1: AztecAddressLike, amount1: (bigint | number), nonce1: FieldLike, to2: AztecAddressLike, amount2: (bigint | number), nonce2: FieldLike, to3: AztecAddressLike, amount3: (bigint | number), nonce3: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** pay_two(to1: struct, amount1: integer, nonce1: field, to2: struct, amount2: integer, nonce2: field) */
    pay_two: ((to1: AztecAddressLike, amount1: (bigint | number), nonce1: FieldLike, to2: AztecAddressLike, amount2: (bigint | number), nonce2: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
