
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import BattleshipPvPContractArtifactJson from '../../contracts/target/battleship_pvp-BattleshipPvP.json' with { type: 'json' };
export const BattleshipPvPContractArtifact = loadContractArtifact(BattleshipPvPContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract BattleshipPvP;
 */
export class BattleshipPvPContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, BattleshipPvPContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): BattleshipPvPContract {
    return Contract.at(address, BattleshipPvPContract.artifact, wallet) as BattleshipPvPContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<BattleshipPvPContract>(
      wallet,
      {
        artifact: BattleshipPvPContractArtifact,
        postDeployCtor: (instance, wallet) => BattleshipPvPContract.at(instance.address, wallet),
        args: [],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BattleshipPvPContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<BattleshipPvPContract['methods'][M]>
  ) {
    return DeployMethod.create<BattleshipPvPContract>(
      opts.wallet,
      {
        artifact: BattleshipPvPContractArtifact,
        postDeployCtor: (instance, wallet) => BattleshipPvPContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BattleshipPvPContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(BattleshipPvPContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'player_a' | 'player_b' | 'commit_a' | 'commit_b' | 'status' | 'turn' | 'pending_cell' | 'pending_shooter' | 'hits_a' | 'hits_b' | 'game_count'> {
      return {
        player_a: {
      slot: new Fr(1n),
    },
player_b: {
      slot: new Fr(2n),
    },
commit_a: {
      slot: new Fr(3n),
    },
commit_b: {
      slot: new Fr(4n),
    },
status: {
      slot: new Fr(5n),
    },
turn: {
      slot: new Fr(6n),
    },
pending_cell: {
      slot: new Fr(7n),
    },
pending_shooter: {
      slot: new Fr(8n),
    },
hits_a: {
      slot: new Fr(9n),
    },
hits_b: {
      slot: new Fr(10n),
    },
game_count: {
      slot: new Fr(11n),
    }
      } as ContractStorageLayout<'player_a' | 'player_b' | 'commit_a' | 'commit_b' | 'status' | 'turn' | 'pending_cell' | 'pending_shooter' | 'hits_a' | 'hits_b' | 'game_count'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** answer(game_id: field, c0: integer, c1: integer, salt: field, pending_cell_claim: integer) */
    answer: ((game_id: FieldLike, c0: (bigint | number), c1: (bigint | number), salt: FieldLike, pending_cell_claim: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_game(fleet_commitment: field, salt: field) */
    create_game: ((fleet_commitment: FieldLike, salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** fire(game_id: field, cell: integer) */
    fire: ((game_id: FieldLike, cell: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hits_a(game_id: field) */
    get_hits_a: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hits_b(game_id: field) */
    get_hits_b: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pending_cell(game_id: field) */
    get_pending_cell: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_pending_shooter(game_id: field) */
    get_pending_shooter: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_status(game_id: field) */
    get_status: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_turn(game_id: field) */
    get_turn: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init() */
    init: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** join_game(game_id: field, fleet_commitment: field) */
    join_game: ((game_id: FieldLike, fleet_commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
