
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import BattleshipContractArtifactJson from '../../contracts/target/battleship-Battleship.json' with { type: 'json' };
export const BattleshipContractArtifact = loadContractArtifact(BattleshipContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Battleship;
 */
export class BattleshipContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, BattleshipContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): BattleshipContract {
    return Contract.at(address, BattleshipContract.artifact, wallet) as BattleshipContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, payment_token: AztecAddressLike, operator: AztecAddressLike) {
    return new DeployMethod<BattleshipContract>(PublicKeys.default(), wallet, BattleshipContractArtifact, (instance, wallet) => BattleshipContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, payment_token: AztecAddressLike, operator: AztecAddressLike) {
    return new DeployMethod<BattleshipContract>(publicKeys, wallet, BattleshipContractArtifact, (instance, wallet) => BattleshipContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BattleshipContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<BattleshipContract['methods'][M]>
  ) {
    return new DeployMethod<BattleshipContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      BattleshipContractArtifact,
      (instance, wallet) => BattleshipContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BattleshipContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(BattleshipContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'payment_token' | 'operator' | 'shots_mask' | 'shots_fired' | 'hits' | 'game_status'> {
      return {
        payment_token: {
      slot: new Fr(1n),
    },
operator: {
      slot: new Fr(3n),
    },
shots_mask: {
      slot: new Fr(5n),
    },
shots_fired: {
      slot: new Fr(6n),
    },
hits: {
      slot: new Fr(7n),
    },
game_status: {
      slot: new Fr(8n),
    }
      } as ContractStorageLayout<'payment_token' | 'operator' | 'shots_mask' | 'shots_fired' | 'hits' | 'game_status'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** fire(game_id: field, cell_index: integer) */
    fire: ((game_id: FieldLike, cell_index: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hits(game_id: field) */
    get_hits: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_shots_mask(game_id: field) */
    get_shots_mask: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_status(game_id: field) */
    get_status: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(payment_token: struct, operator: struct) */
    init: ((payment_token: AztecAddressLike, operator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** start_game(salt: field, authwit_nonce: field) */
    start_game: ((salt: FieldLike, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
