
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import BlackjackContractArtifactJson from '../../contracts/target/blackjack-Blackjack.json' with { type: 'json' };
export const BlackjackContractArtifact = loadContractArtifact(BlackjackContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Blackjack;
 */
export class BlackjackContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, BlackjackContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): BlackjackContract {
    return Contract.at(address, BlackjackContract.artifact, wallet) as BlackjackContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, dealer: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<BlackjackContract>(
      wallet,
      {
        artifact: BlackjackContractArtifact,
        postDeployCtor: (instance, wallet) => BlackjackContract.at(instance.address, wallet),
        args: [dealer],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BlackjackContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<BlackjackContract['methods'][M]>
  ) {
    return DeployMethod.create<BlackjackContract>(
      opts.wallet,
      {
        artifact: BlackjackContractArtifact,
        postDeployCtor: (instance, wallet) => BlackjackContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BlackjackContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(BlackjackContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'dealer' | 'status' | 'player_commit' | 'dealer_commit' | 'deck_root' | 'deck_salt' | 'player_total' | 'dealer_total' | 'outcome' | 'games_settled'> {
      return {
        dealer: {
      slot: new Fr(1n),
    },
status: {
      slot: new Fr(3n),
    },
player_commit: {
      slot: new Fr(4n),
    },
dealer_commit: {
      slot: new Fr(5n),
    },
deck_root: {
      slot: new Fr(6n),
    },
deck_salt: {
      slot: new Fr(7n),
    },
player_total: {
      slot: new Fr(8n),
    },
dealer_total: {
      slot: new Fr(9n),
    },
outcome: {
      slot: new Fr(10n),
    },
games_settled: {
      slot: new Fr(11n),
    }
      } as ContractStorageLayout<'dealer' | 'status' | 'player_commit' | 'dealer_commit' | 'deck_root' | 'deck_salt' | 'player_total' | 'dealer_total' | 'outcome' | 'games_settled'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** commit(game_id: field, player_commit: field) */
    commit: ((game_id: FieldLike, player_commit: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_dealer_total(game_id: field) */
    get_dealer_total: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_games_settled() */
    get_games_settled: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_outcome(game_id: field) */
    get_outcome: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_player_total(game_id: field) */
    get_player_total: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_status(game_id: field) */
    get_status: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(dealer: struct) */
    init: ((dealer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** settle(game_id: field, deck_root: field, deck_salt: field, p_cards: array, p_count: integer, p_paths: array, d_cards: array, d_count: integer, d_paths: array) */
    settle: ((game_id: FieldLike, deck_root: FieldLike, deck_salt: FieldLike, p_cards: FieldLike[], p_count: (bigint | number), p_paths: FieldLike[][], d_cards: FieldLike[], d_count: (bigint | number), d_paths: FieldLike[][]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** start_hand(game_id: field, dealer_commit: field, deck_root: field, deck_salt: field) */
    start_hand: ((game_id: FieldLike, dealer_commit: FieldLike, deck_root: FieldLike, deck_salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
