
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import GoodsEscrowContractArtifactJson from '../../contracts/target/goods_escrow-GoodsEscrow.json' with { type: 'json' };
export const GoodsEscrowContractArtifact = loadContractArtifact(GoodsEscrowContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract GoodsEscrow;
 */
export class GoodsEscrowContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, GoodsEscrowContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): GoodsEscrowContract {
    return Contract.at(address, GoodsEscrowContract.artifact, wallet) as GoodsEscrowContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, payment_token: AztecAddressLike, attestor: AztecAddressLike) {
    return new DeployMethod<GoodsEscrowContract>(PublicKeys.default(), wallet, GoodsEscrowContractArtifact, (instance, wallet) => GoodsEscrowContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, payment_token: AztecAddressLike, attestor: AztecAddressLike) {
    return new DeployMethod<GoodsEscrowContract>(publicKeys, wallet, GoodsEscrowContractArtifact, (instance, wallet) => GoodsEscrowContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof GoodsEscrowContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<GoodsEscrowContract['methods'][M]>
  ) {
    return new DeployMethod<GoodsEscrowContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      GoodsEscrowContractArtifact,
      (instance, wallet) => GoodsEscrowContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return GoodsEscrowContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(GoodsEscrowContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'payment_token' | 'attestor' | 'escrow_count' | 'released_count' | 'amount' | 'item_hash' | 'status' | 'deadline' | 'used_orders'> {
      return {
        payment_token: {
      slot: new Fr(1n),
    },
attestor: {
      slot: new Fr(3n),
    },
escrow_count: {
      slot: new Fr(5n),
    },
released_count: {
      slot: new Fr(6n),
    },
amount: {
      slot: new Fr(7n),
    },
item_hash: {
      slot: new Fr(8n),
    },
status: {
      slot: new Fr(9n),
    },
deadline: {
      slot: new Fr(10n),
    },
used_orders: {
      slot: new Fr(11n),
    }
      } as ContractStorageLayout<'payment_token' | 'attestor' | 'escrow_count' | 'released_count' | 'amount' | 'item_hash' | 'status' | 'deadline' | 'used_orders'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** attest_delivery(escrow_id: field, fulfiller: struct) */
    attest_delivery: ((escrow_id: FieldLike, fulfiller: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** attest_purchase(escrow_id: field, order_id_hash: field) */
    attest_purchase: ((escrow_id: FieldLike, order_id_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_escrow(amount: integer, item_hash: field, deadline: integer, salt: field, authwit_nonce: field) */
    create_escrow: ((amount: (bigint | number), item_hash: FieldLike, deadline: (bigint | number), salt: FieldLike, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_amount(escrow_id: field) */
    get_amount: ((escrow_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_escrow_count() */
    get_escrow_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_released_count() */
    get_released_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_status(escrow_id: field) */
    get_status: ((escrow_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(payment_token: struct, attestor: struct) */
    init: ((payment_token: AztecAddressLike, attestor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** refund(salt: field) */
    refund: ((salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
