
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import IdentityAttestationContractArtifactJson from '../../contracts/target/identity_attestation-IdentityAttestation.json' with { type: 'json' };
export const IdentityAttestationContractArtifact = loadContractArtifact(IdentityAttestationContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract IdentityAttestation;
 */
export class IdentityAttestationContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, IdentityAttestationContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): IdentityAttestationContract {
    return Contract.at(address, IdentityAttestationContract.artifact, wallet) as IdentityAttestationContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, issuer: AztecAddressLike) {
    return new DeployMethod<IdentityAttestationContract>(PublicKeys.default(), wallet, IdentityAttestationContractArtifact, (instance, wallet) => IdentityAttestationContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, issuer: AztecAddressLike) {
    return new DeployMethod<IdentityAttestationContract>(publicKeys, wallet, IdentityAttestationContractArtifact, (instance, wallet) => IdentityAttestationContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof IdentityAttestationContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<IdentityAttestationContract['methods'][M]>
  ) {
    return new DeployMethod<IdentityAttestationContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      IdentityAttestationContractArtifact,
      (instance, wallet) => IdentityAttestationContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return IdentityAttestationContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(IdentityAttestationContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'issuer' | 'credentials' | 'total_issued' | 'total_proven'> {
      return {
        issuer: {
      slot: new Fr(1n),
    },
credentials: {
      slot: new Fr(3n),
    },
total_issued: {
      slot: new Fr(4n),
    },
total_proven: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'issuer' | 'credentials' | 'total_issued' | 'total_proven'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_credential(commitment: field) */
    add_credential: ((commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_slot_status(commitment: field) */
    get_slot_status: ((commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_issued() */
    get_total_issued: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_proven() */
    get_total_proven: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(issuer: struct) */
    init: ((issuer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** prove_membership(secret: field) */
    prove_membership: ((secret: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
