
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import LotteryContractArtifactJson from '../../contracts/target/lottery-Lottery.json' with { type: 'json' };
export const LotteryContractArtifact = loadContractArtifact(LotteryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Lottery;
 */
export class LotteryContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, LotteryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): LotteryContract {
    return Contract.at(address, LotteryContract.artifact, wallet) as LotteryContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, payment_token: AztecAddressLike, operator: AztecAddressLike, vrf_portal: EthAddressLike, seed_commitment: FieldLike) {
    return new DeployMethod<LotteryContract>(PublicKeys.default(), wallet, LotteryContractArtifact, (instance, wallet) => LotteryContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, payment_token: AztecAddressLike, operator: AztecAddressLike, vrf_portal: EthAddressLike, seed_commitment: FieldLike) {
    return new DeployMethod<LotteryContract>(publicKeys, wallet, LotteryContractArtifact, (instance, wallet) => LotteryContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof LotteryContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<LotteryContract['methods'][M]>
  ) {
    return new DeployMethod<LotteryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      LotteryContractArtifact,
      (instance, wallet) => LotteryContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return LotteryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(LotteryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'payment_token' | 'operator' | 'vrf_portal' | 'seed_commitment' | 'phase' | 'ticket_count' | 'winning_number' | 'winners_count' | 'tickets'> {
      return {
        payment_token: {
      slot: new Fr(1n),
    },
operator: {
      slot: new Fr(3n),
    },
vrf_portal: {
      slot: new Fr(5n),
    },
seed_commitment: {
      slot: new Fr(7n),
    },
phase: {
      slot: new Fr(9n),
    },
ticket_count: {
      slot: new Fr(10n),
    },
winning_number: {
      slot: new Fr(11n),
    },
winners_count: {
      slot: new Fr(12n),
    },
tickets: {
      slot: new Fr(13n),
    }
      } as ContractStorageLayout<'payment_token' | 'operator' | 'vrf_portal' | 'seed_commitment' | 'phase' | 'ticket_count' | 'winning_number' | 'winners_count' | 'tickets'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** buy_ticket(number: integer, salt: field, authwit_nonce: field) */
    buy_ticket: ((number: (bigint | number), salt: FieldLike, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_prize(number: integer, salt: field) */
    claim_prize: ((number: (bigint | number), salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** close_round() */
    close_round: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** finalize_draw(seed: field, salt: field) */
    finalize_draw: ((seed: FieldLike, salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_phase() */
    get_phase: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_ticket_count() */
    get_ticket_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_winners_count() */
    get_winners_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_winning_number() */
    get_winning_number: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(payment_token: struct, operator: struct, vrf_portal: struct, seed_commitment: field) */
    init: ((payment_token: AztecAddressLike, operator: AztecAddressLike, vrf_portal: EthAddressLike, seed_commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** request_draw() */
    request_draw: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
