
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MinesweeperContractArtifactJson from '../../contracts/target/minesweeper-Minesweeper.json' with { type: 'json' };
export const MinesweeperContractArtifact = loadContractArtifact(MinesweeperContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Minesweeper;
 */
export class MinesweeperContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MinesweeperContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MinesweeperContract {
    return Contract.at(address, MinesweeperContract.artifact, wallet) as MinesweeperContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, payment_token: AztecAddressLike, operator: AztecAddressLike) {
    return new DeployMethod<MinesweeperContract>(PublicKeys.default(), wallet, MinesweeperContractArtifact, (instance, wallet) => MinesweeperContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, payment_token: AztecAddressLike, operator: AztecAddressLike) {
    return new DeployMethod<MinesweeperContract>(publicKeys, wallet, MinesweeperContractArtifact, (instance, wallet) => MinesweeperContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MinesweeperContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MinesweeperContract['methods'][M]>
  ) {
    return new DeployMethod<MinesweeperContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MinesweeperContractArtifact,
      (instance, wallet) => MinesweeperContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MinesweeperContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MinesweeperContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'payment_token' | 'operator' | 'revealed_mask' | 'game_status' | 'mines_hit' | 'safe_revealed'> {
      return {
        payment_token: {
      slot: new Fr(1n),
    },
operator: {
      slot: new Fr(3n),
    },
revealed_mask: {
      slot: new Fr(5n),
    },
game_status: {
      slot: new Fr(6n),
    },
mines_hit: {
      slot: new Fr(7n),
    },
safe_revealed: {
      slot: new Fr(8n),
    }
      } as ContractStorageLayout<'payment_token' | 'operator' | 'revealed_mask' | 'game_status' | 'mines_hit' | 'safe_revealed'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** claim_win(game_id: field, expected_mine_count: integer) */
    claim_win: ((game_id: FieldLike, expected_mine_count: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_revealed_mask(game_id: field) */
    get_revealed_mask: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_safe_revealed(game_id: field) */
    get_safe_revealed: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_status(game_id: field) */
    get_status: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(payment_token: struct, operator: struct) */
    init: ((payment_token: AztecAddressLike, operator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** reveal(game_id: field, cell_index: integer) */
    reveal: ((game_id: FieldLike, cell_index: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** start_game(salt: field, authwit_nonce: field) */
    start_game: ((salt: FieldLike, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
