
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import PayrollContractArtifactJson from '../../contracts/target/payroll-Payroll.json' with { type: 'json' };
export const PayrollContractArtifact = loadContractArtifact(PayrollContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Payroll;
 */
export class PayrollContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, PayrollContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PayrollContract {
    return Contract.at(address, PayrollContract.artifact, wallet) as PayrollContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, payment_token: AztecAddressLike, operator: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<PayrollContract>(
      wallet,
      {
        artifact: PayrollContractArtifact,
        postDeployCtor: (instance, wallet) => PayrollContract.at(instance.address, wallet),
        args: [payment_token, operator],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PayrollContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<PayrollContract['methods'][M]>
  ) {
    return DeployMethod.create<PayrollContract>(
      opts.wallet,
      {
        artifact: PayrollContractArtifact,
        postDeployCtor: (instance, wallet) => PayrollContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PayrollContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PayrollContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'payment_token' | 'operator' | 'period' | 'total_funded' | 'payslip_count' | 'claimed_count' | 'payslips'> {
      return {
        payment_token: {
      slot: new Fr(1n),
    },
operator: {
      slot: new Fr(3n),
    },
period: {
      slot: new Fr(5n),
    },
total_funded: {
      slot: new Fr(6n),
    },
payslip_count: {
      slot: new Fr(7n),
    },
claimed_count: {
      slot: new Fr(8n),
    },
payslips: {
      slot: new Fr(9n),
    }
      } as ContractStorageLayout<'payment_token' | 'operator' | 'period' | 'total_funded' | 'payslip_count' | 'claimed_count' | 'payslips'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_payslip(commitment: field) */
    add_payslip: ((commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** advance_period() */
    advance_period: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim(amount: integer, period: integer, recipient: struct) */
    claim: ((amount: (bigint | number), period: (bigint | number), recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** demo_add_payslip(commitment: field) */
    demo_add_payslip: ((commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** fund(amount: integer, authwit_nonce: field) */
    fund: ((amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_claimed_count() */
    get_claimed_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_payslip_count() */
    get_payslip_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_period() */
    get_period: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_slot_status(commitment: field) */
    get_slot_status: ((commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_funded() */
    get_total_funded: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(payment_token: struct, operator: struct) */
    init: ((payment_token: AztecAddressLike, operator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
