
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import PerDonorReceiptsContractArtifactJson from '../../contracts/target/per_donor_receipts-PerDonorReceipts.json' with { type: 'json' };
export const PerDonorReceiptsContractArtifact = loadContractArtifact(PerDonorReceiptsContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract PerDonorReceipts;
 */
export class PerDonorReceiptsContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, PerDonorReceiptsContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PerDonorReceiptsContract {
    return Contract.at(address, PerDonorReceiptsContract.artifact, wallet) as PerDonorReceiptsContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, donation_token: AztecAddressLike, operator: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<PerDonorReceiptsContract>(
      wallet,
      {
        artifact: PerDonorReceiptsContractArtifact,
        postDeployCtor: (instance, wallet) => PerDonorReceiptsContract.at(instance.address, wallet),
        args: [donation_token, operator],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PerDonorReceiptsContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<PerDonorReceiptsContract['methods'][M]>
  ) {
    return DeployMethod.create<PerDonorReceiptsContract>(
      opts.wallet,
      {
        artifact: PerDonorReceiptsContractArtifact,
        postDeployCtor: (instance, wallet) => PerDonorReceiptsContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PerDonorReceiptsContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PerDonorReceiptsContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'donation_token' | 'operator' | 'total_raised' | 'receipts'> {
      return {
        donation_token: {
      slot: new Fr(1n),
    },
operator: {
      slot: new Fr(3n),
    },
total_raised: {
      slot: new Fr(5n),
    },
receipts: {
      slot: new Fr(6n),
    }
      } as ContractStorageLayout<'donation_token' | 'operator' | 'total_raised' | 'receipts'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** donate_with_receipt(amount: integer, salt: field, authwit_nonce: field) */
    donate_with_receipt: ((amount: (bigint | number), salt: FieldLike, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_receipt(receipt_key: field) */
    get_receipt: ((receipt_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_raised() */
    get_total_raised: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(donation_token: struct, operator: struct) */
    init: ((donation_token: AztecAddressLike, operator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
