
/* Autogenerated file, do not edit! */
// @ts-nocheck

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import PublicTotalCrowdfundingContractArtifactJson from '../../contracts/target/public_total_crowdfunding-PublicTotalCrowdfunding.json' with { type: 'json' };
export const PublicTotalCrowdfundingContractArtifact = loadContractArtifact(PublicTotalCrowdfundingContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract PublicTotalCrowdfunding;
 */
export class PublicTotalCrowdfundingContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, PublicTotalCrowdfundingContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PublicTotalCrowdfundingContract {
    return Contract.at(address, PublicTotalCrowdfundingContract.artifact, wallet) as PublicTotalCrowdfundingContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, donation_token: AztecAddressLike, operator: AztecAddressLike) {
    return new DeployMethod<PublicTotalCrowdfundingContract>(PublicKeys.default(), wallet, PublicTotalCrowdfundingContractArtifact, (instance, wallet) => PublicTotalCrowdfundingContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, donation_token: AztecAddressLike, operator: AztecAddressLike) {
    return new DeployMethod<PublicTotalCrowdfundingContract>(publicKeys, wallet, PublicTotalCrowdfundingContractArtifact, (instance, wallet) => PublicTotalCrowdfundingContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PublicTotalCrowdfundingContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PublicTotalCrowdfundingContract['methods'][M]>
  ) {
    return new DeployMethod<PublicTotalCrowdfundingContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PublicTotalCrowdfundingContractArtifact,
      (instance, wallet) => PublicTotalCrowdfundingContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PublicTotalCrowdfundingContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PublicTotalCrowdfundingContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'donation_token' | 'operator' | 'total_raised'> {
      return {
        donation_token: {
      slot: new Fr(1n),
    },
operator: {
      slot: new Fr(3n),
    },
total_raised: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'donation_token' | 'operator' | 'total_raised'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** donate(amount: integer, authwit_nonce: field) */
    donate: ((amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_raised() */
    get_total_raised: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(donation_token: struct, operator: struct) */
    init: ((donation_token: AztecAddressLike, operator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
