
/* Autogenerated file, do not edit! */
// @ts-nocheck

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import PublicCollateralPrivateDebtContractArtifactJson from '../../contracts/target/public_collateral_private_debt-PublicCollateralPrivateDebt.json' with { type: 'json' };
export const PublicCollateralPrivateDebtContractArtifact = loadContractArtifact(PublicCollateralPrivateDebtContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract PublicCollateralPrivateDebt;
 */
export class PublicCollateralPrivateDebtContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, PublicCollateralPrivateDebtContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PublicCollateralPrivateDebtContract {
    return Contract.at(address, PublicCollateralPrivateDebtContract.artifact, wallet) as PublicCollateralPrivateDebtContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, collateral_token: AztecAddressLike, debt_token: AztecAddressLike, operator: AztecAddressLike) {
    return new DeployMethod<PublicCollateralPrivateDebtContract>(PublicKeys.default(), wallet, PublicCollateralPrivateDebtContractArtifact, (instance, wallet) => PublicCollateralPrivateDebtContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, collateral_token: AztecAddressLike, debt_token: AztecAddressLike, operator: AztecAddressLike) {
    return new DeployMethod<PublicCollateralPrivateDebtContract>(publicKeys, wallet, PublicCollateralPrivateDebtContractArtifact, (instance, wallet) => PublicCollateralPrivateDebtContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PublicCollateralPrivateDebtContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PublicCollateralPrivateDebtContract['methods'][M]>
  ) {
    return new DeployMethod<PublicCollateralPrivateDebtContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PublicCollateralPrivateDebtContractArtifact,
      (instance, wallet) => PublicCollateralPrivateDebtContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PublicCollateralPrivateDebtContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PublicCollateralPrivateDebtContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'collateral_token' | 'debt_token' | 'operator' | 'collateral' | 'debt' | 'total_collateral'> {
      return {
        collateral_token: {
      slot: new Fr(1n),
    },
debt_token: {
      slot: new Fr(3n),
    },
operator: {
      slot: new Fr(5n),
    },
collateral: {
      slot: new Fr(7n),
    },
debt: {
      slot: new Fr(8n),
    },
total_collateral: {
      slot: new Fr(9n),
    }
      } as ContractStorageLayout<'collateral_token' | 'debt_token' | 'operator' | 'collateral' | 'debt' | 'total_collateral'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** borrow_private(secret: field, owner: struct, amount: integer) */
    borrow_private: ((secret: FieldLike, owner: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deposit_public(amount: integer, commitment: field, authwit_nonce: field) */
    deposit_public: ((amount: (bigint | number), commitment: FieldLike, authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_collateral(commitment: field) */
    get_collateral: ((commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_debt(commitment: field) */
    get_debt: ((commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_collateral() */
    get_total_collateral: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(collateral_token: struct, debt_token: struct, operator: struct) */
    init: ((collateral_token: AztecAddressLike, debt_token: AztecAddressLike, operator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
