
/* Autogenerated file, do not edit! */

// @ts-nocheck

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import RewardsContractArtifactJson from '../../contracts/target/rewards-Rewards.json' with { type: 'json' };
export const RewardsContractArtifact = loadContractArtifact(RewardsContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Rewards;
 */
export class RewardsContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, RewardsContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): RewardsContract {
    return Contract.at(address, RewardsContract.artifact, wallet) as RewardsContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, payment_token: AztecAddressLike, operator: AztecAddressLike) {
    return new DeployMethod<RewardsContract>(PublicKeys.default(), wallet, RewardsContractArtifact, (instance, wallet) => RewardsContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, payment_token: AztecAddressLike, operator: AztecAddressLike) {
    return new DeployMethod<RewardsContract>(publicKeys, wallet, RewardsContractArtifact, (instance, wallet) => RewardsContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof RewardsContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<RewardsContract['methods'][M]>
  ) {
    return new DeployMethod<RewardsContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      RewardsContractArtifact,
      (instance, wallet) => RewardsContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return RewardsContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(RewardsContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'payment_token' | 'operator' | 'root' | 'period' | 'total_claimed' | 'claimed'> {
      return {
        payment_token: {
      slot: new Fr(1n),
    },
operator: {
      slot: new Fr(3n),
    },
root: {
      slot: new Fr(5n),
    },
period: {
      slot: new Fr(6n),
    },
total_claimed: {
      slot: new Fr(7n),
    },
claimed: {
      slot: new Fr(8n),
    }
      } as ContractStorageLayout<'payment_token' | 'operator' | 'root' | 'period' | 'total_claimed' | 'claimed'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** advance_period() */
    advance_period: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_private(amount: integer, period: integer, leaf_index: field, sibling_path: array, recipient: struct) */
    claim_private: ((amount: (bigint | number), period: (bigint | number), leaf_index: FieldLike, sibling_path: FieldLike[], recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_public(amount: integer, period: integer, leaf_index: field, sibling_path: array, recipient: struct) */
    claim_public: ((amount: (bigint | number), period: (bigint | number), leaf_index: FieldLike, sibling_path: FieldLike[], recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** demo_claim(recipient: struct) */
    demo_claim: ((recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_period() */
    get_period: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_root() */
    get_root: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_claimed() */
    get_total_claimed: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(payment_token: struct, operator: struct) */
    init: ((payment_token: AztecAddressLike, operator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_claimed(leaf: field) */
    is_claimed: ((leaf: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** publish_root(new_root: field) */
    publish_root: ((new_root: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
