
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import SealedBidAuctionContractArtifactJson from '../../contracts/target/sealed_bid_auction-SealedBidAuction.json' with { type: 'json' };
export const SealedBidAuctionContractArtifact = loadContractArtifact(SealedBidAuctionContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract SealedBidAuction;
 */
export class SealedBidAuctionContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, SealedBidAuctionContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): SealedBidAuctionContract {
    return Contract.at(address, SealedBidAuctionContract.artifact, wallet) as SealedBidAuctionContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, operator: AztecAddressLike, item_hash: FieldLike, bid_deadline: (bigint | number), reveal_deadline: (bigint | number)) {
    return new DeployMethod<SealedBidAuctionContract>(PublicKeys.default(), wallet, SealedBidAuctionContractArtifact, (instance, wallet) => SealedBidAuctionContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, operator: AztecAddressLike, item_hash: FieldLike, bid_deadline: (bigint | number), reveal_deadline: (bigint | number)) {
    return new DeployMethod<SealedBidAuctionContract>(publicKeys, wallet, SealedBidAuctionContractArtifact, (instance, wallet) => SealedBidAuctionContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof SealedBidAuctionContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<SealedBidAuctionContract['methods'][M]>
  ) {
    return new DeployMethod<SealedBidAuctionContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      SealedBidAuctionContractArtifact,
      (instance, wallet) => SealedBidAuctionContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return SealedBidAuctionContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(SealedBidAuctionContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'operator' | 'item_hash' | 'bid_deadline' | 'reveal_deadline' | 'commitments' | 'bid_count' | 'revealed_count' | 'winning_bid' | 'winner' | 'settled'> {
      return {
        operator: {
      slot: new Fr(1n),
    },
item_hash: {
      slot: new Fr(3n),
    },
bid_deadline: {
      slot: new Fr(5n),
    },
reveal_deadline: {
      slot: new Fr(7n),
    },
commitments: {
      slot: new Fr(9n),
    },
bid_count: {
      slot: new Fr(10n),
    },
revealed_count: {
      slot: new Fr(11n),
    },
winning_bid: {
      slot: new Fr(12n),
    },
winner: {
      slot: new Fr(13n),
    },
settled: {
      slot: new Fr(14n),
    }
      } as ContractStorageLayout<'operator' | 'item_hash' | 'bid_deadline' | 'reveal_deadline' | 'commitments' | 'bid_count' | 'revealed_count' | 'winning_bid' | 'winner' | 'settled'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** get_bid_count() */
    get_bid_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_commitment_status(commitment: field) */
    get_commitment_status: ((commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_revealed_count() */
    get_revealed_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_settled() */
    get_settled: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_winner() */
    get_winner: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_winning_bid() */
    get_winning_bid: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(operator: struct, item_hash: field, bid_deadline: integer, reveal_deadline: integer) */
    init: ((operator: AztecAddressLike, item_hash: FieldLike, bid_deadline: (bigint | number), reveal_deadline: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** place_bid(amount: integer, salt: field) */
    place_bid: ((amount: (bigint | number), salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** reveal_bid(amount: integer, salt: field) */
    reveal_bid: ((amount: (bigint | number), salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** settle() */
    settle: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
