
/* Autogenerated file, do not edit! */

// @ts-nocheck
/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import WordleContractArtifactJson from '../../contracts/target/wordle-Wordle.json' with { type: 'json' };
export const WordleContractArtifact = loadContractArtifact(WordleContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Wordle;
 */
export class WordleContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, WordleContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): WordleContract {
    return Contract.at(address, WordleContract.artifact, wallet) as WordleContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, operator: AztecAddressLike, challenge_hash: FieldLike, guess_deadline: (bigint | number), reveal_deadline: (bigint | number)) {
    return new DeployMethod<WordleContract>(PublicKeys.default(), wallet, WordleContractArtifact, (instance, wallet) => WordleContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, operator: AztecAddressLike, challenge_hash: FieldLike, guess_deadline: (bigint | number), reveal_deadline: (bigint | number)) {
    return new DeployMethod<WordleContract>(publicKeys, wallet, WordleContractArtifact, (instance, wallet) => WordleContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof WordleContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<WordleContract['methods'][M]>
  ) {
    return new DeployMethod<WordleContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      WordleContractArtifact,
      (instance, wallet) => WordleContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return WordleContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(WordleContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'operator' | 'challenge_hash' | 'guess_deadline' | 'reveal_deadline' | 'challenge_revealed' | 'guess_commitments' | 'player_attempts' | 'player_solved_on' | 'total_solvers'> {
      return {
        operator: {
      slot: new Fr(1n),
    },
challenge_hash: {
      slot: new Fr(3n),
    },
guess_deadline: {
      slot: new Fr(5n),
    },
reveal_deadline: {
      slot: new Fr(7n),
    },
challenge_revealed: {
      slot: new Fr(9n),
    },
guess_commitments: {
      slot: new Fr(10n),
    },
player_attempts: {
      slot: new Fr(11n),
    },
player_solved_on: {
      slot: new Fr(12n),
    },
total_solvers: {
      slot: new Fr(13n),
    }
      } as ContractStorageLayout<'operator' | 'challenge_hash' | 'guess_deadline' | 'reveal_deadline' | 'challenge_revealed' | 'guess_commitments' | 'player_attempts' | 'player_solved_on' | 'total_solvers'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** get_attempts(player: struct) */
    get_attempts: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_challenge_revealed() */
    get_challenge_revealed: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_solved_on(player: struct) */
    get_solved_on: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_solvers() */
    get_total_solvers: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** init(operator: struct, challenge_hash: field, guess_deadline: integer, reveal_deadline: integer) */
    init: ((operator: AztecAddressLike, challenge_hash: FieldLike, guess_deadline: (bigint | number), reveal_deadline: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** prove_solve(word_packed: field, salt: field) */
    prove_solve: ((word_packed: FieldLike, salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** reveal_target(word_packed: field, salt: field) */
    reveal_target: ((word_packed: FieldLike, salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** submit_guess(word_packed: field, salt: field) */
    submit_guess: ((word_packed: FieldLike, salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
